---
- name: Flatpak | Install flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Flatpak | Install Plasma Discover backend
  ansible.builtin.apt:
    name: plasma-discover-backend-flatpak
    state: present
  when: flatpak_plasmashell_check.rc == 0