---
- name: "Flatpak | Run tasks for {{ ansible_facts.os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Flatpak | Add remotes
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.url }}"
    state: present
  loop: "{{ flatpak_remotes }}"

- name: Flatpak | Install apps
  community.general.flatpak:
    name: "{{ flatpak_apps }}"
    state: present
    remote: flathub
  vars:
    flatpak_apps: >-
      {{
        shared_flatpaks +
        distro_flatpaks +
        (gaming_enabled | ternary(gaming_flatpaks, []))
      }}
  when:
    - flatpak_apps | length > 0
