---
- name: Flatpak | Install package manager
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Flatpak
    install_pacman_packages: "{{ flatpak_pacman_packages }}"

- name: Flatpak | Add remotes
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.url }}"
    state: present
  loop: "{{ flatpak_remotes }}"

- name: Flatpak | Install apps
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Flatpak apps
    install_flatpak_packages: "{{ flatpak_apps }}"
