---
- name: Fail2ban | Run Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: Fail2ban | Run Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Fail2ban | Deploy jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Fail2ban | Enable and start service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
