---
- name: "Fail2ban | Run {{ ansible_facts.os_family }} tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Fail2ban | Deploy jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Fail2ban | Restart fail2ban

- name: Fail2ban | Enable and start service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
