---
hyprland_config_dir: "{{ user_home }}/.config/hypr"
hyprland_kb_layout: us
monitors: []

hyprland_packages:
  # Core compositor
  - hyprland
  - xdg-desktop-portal-hyprland

  # Status bar / launcher
  - waybar
  - rofi

  # Terminal
  - kitty

  # Wayland utilities
  - wl-clipboard
  - grim
  - slurp
  - brightnessctl

  # Media controls
  - playerctl
  - pavucontrol

  # Network / tray
  - network-manager-applet

  # Lock + idle
  - swaylock
  - swayidle

  # Wallpaper
  - hyprpaper
