---
hyprland_packages:
  - hyprland
  - xdg-desktop-portal-hyprland
  - waybar
  - rofi
  - kitty
  - wl-clipboard
  - grim
  - slurp
  - brightnessctl
  - playerctl
  - pavucontrol
  - network-manager-applet
  - swaylock
  - swayidle
  - hyprpaper
