---
browser_debian_keyring_path: /usr/share/keyrings/brave-browser-archive-keyring.gpg
browser_debian_sources_path: /etc/apt/sources.list.d/brave-browser-release.sources
browser_debian_keyring_url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
browser_debian_sources_url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
browser_debian_package: brave-browser
browser_arch_package: brave-bin
browser_policy_dir: /etc/brave/policies/managed
browser_policy_file: zz-browser-policy.json
browser_extensions:
  - name: Bitwarden
    id: nngceckbapebfimnlniiiahkandclblb
    update_url: https://clients2.google.com/service/update2/crx
  - name: Smooth Key Scroll
    id: gphmhpfbknciemgfnfhjapilmcaecljh
    update_url: https://clients2.google.com/service/update2/crx
  - name: Stylus
    id: clngdbkpkpeebahjckkjfobafhncgmne
    update_url: https://clients2.google.com/service/update2/crx
  - name: Animouto
    id: ilhjhegbgdghfkdgeahkpikkjgaaoklh
    update_url: https://clients2.google.com/service/update2/crx
  - name: Violentmonkey
    id: jinjaccalgkegednnccohejagnlnfdag
    update_url: https://clients2.google.com/service/update2/crx
  - name: Image Downloader
    id: cnpniohnfphhjihaiiggeabnkjhpaldj
    update_url: https://clients2.google.com/service/update2/crx
browser_extra_policies:
  DefaultSearchProviderEnabled: true
  DefaultSearchProviderName: "Google"
  DefaultSearchProviderSearchURL: "https://www.google.com/search?q={searchTerms}"
  DefaultSearchProviderSuggestURL: "https://www.google.com/complete/search?output=chrome&q={searchTerms}"
  RestoreOnStartup: 5
  BraveRewardsDisabled: true
  BraveWalletDisabled: true
