---
browser_debian_keyring_dir: /usr/share/keyrings
browser_debian_keyring_path: "{{ browser_debian_keyring_dir }}/brave-browser-archive-keyring.gpg"
browser_debian_sources_dir: /etc/apt/sources.list.d
browser_debian_sources_path: "{{ browser_debian_sources_dir }}/brave-browser-release.sources"
browser_debian_keyring_url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
browser_debian_sources_url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
browser_debian_package: brave-browser
browser_arch_package: brave-bin
browser_policy_dir: /etc/brave/policies/managed
browser_policy_file: zz-browser-policy.json
browser_extensions:
  - name: Bitwarden
    id: nngceckbapebfimnlniiiahkandclblb
    update_url: https://clients2.google.com/service/update2/crx
  - name: Smooth Key Scroll
    id: gphmhpfbknciemgfnfhjapilmcaecljh
    update_url: https://clients2.google.com/service/update2/crx
  - name: Stylus
    id: clngdbkpkpeebahjckkjfobafhncgmne
    update_url: https://clients2.google.com/service/update2/crx
  - name: Animouto
    id: ilhjhegbgdghfkdgeahkpikkjgaaoklh
    update_url: https://clients2.google.com/service/update2/crx
  - name: Violentmonkey
    id: jinjaccalgkegednnccohejagnlnfdag
    update_url: https://clients2.google.com/service/update2/crx
  - name: Image Downloader
    id: cnpniohnfphhjihaiiggeabnkjhpaldj
    update_url: https://clients2.google.com/service/update2/crx
browser_extra_policies: {}
