---
system_aur_build_packages:
  - base-devel
  - git
  - rust


system_paru_repo: https://aur.archlinux.org/paru.git
system_paru_build_dir: "{{ user_home }}/paru-build"

home_core_packages:
  - curl
  - wget
  - vim
  - htop
  - zsh
  - unzip
  - rsync
  - mpv
  - kitty
  - fastfetch
  - man-db
  - man-pages

home_utility_packages:
  - ncdu
  - ripgrep
  - vulkan-tools
  - fuse2
  - fuse3
  - atuin
  - openssl
  - pamixer
  - xdg-utils
  - plocate
  - psmisc
  - github-cli
  - tmux
  - eza
  - bat
  - fd
  - zoxide
  - fzf
  - lazygit
  - git-delta
  - duf
  - procs
  - just
  - trash-cli
  - neovim

home_media_packages:
  - ffmpeg
  - yt-dlp
  - gimp
  - pavucontrol
  - obs-studio
  - flowblade

home_office_packages:
  - libreoffice-fresh
  - thunderbird

home_system_packages:
  - gparted
  - dconf-editor
  - qbittorrent
  - timeshift
  - keepassxc
  - flatpak-builder

home_fun_packages: []

home_gaming_packages:
  - steam
  - lutris
  - gamemode
  - mangohud
  - goverlay
  - wine
  - winetricks
  - protontricks
  - piper
  - retroarch

home_aur_gaming_packages:
  - celeste-classic
  - celeste-classic-pm

home_dev_packages:
  - git
  - pkgconf
  - python
  - python-pip
  - python-pipx
  - jq
  - yq
  - httpie
  - ansible-lint
  - yamllint
  - shellcheck
  - pre-commit
  - python-playwright
  - gcc
  - gdb
  - cmake

system_fonts_packages:
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - ttf-dejavu
  - ttf-liberation
  - gnu-free-fonts

system_nvidia_packages:
  - nvidia-settings
  - vulkan-icd-loader

system_virtualization_kvm_packages:
  - qemu-full
  - libvirt
  - virt-install
  - virt-manager
  - bridge-utils
  - edk2-ovmf

system_virtualization_virtualbox_packages:
  - virtualbox
  - virtualbox-host-modules-arch

libvirt_service: libvirtd
system_virtualization_user_groups:
  - libvirt
  - kvm

system_pipewire_packages:
  - pipewire
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - wireplumber
  - gst-plugin-pipewire

system_bluetooth_packages:
  - bluez
  - bluez-utils

system_docker_engine_packages:
  - docker

system_docker_plugin_packages:
  - docker-compose
  - docker-buildx

docker_group: docker

system_networking_packages:
  - networkmanager

system_vpn_packages:
  - wireguard-tools
  - openvpn
  - networkmanager-openvpn

system_splashboot_packages:
  - plymouth

ssh_package: openssh
ssh_service: sshd

system_grub_packages_bios:
  - grub

system_grub_packages_uefi:
  - grub
  - efibootmgr

system_grub_bootloader_id: GRUB

home_user_groups:
  - wheel
  - audio
  - video
