---
aur_build_packages:
  - base-devel
  - git
  - rust

hyprland_supported: true
niri_supported: true

paru_repo: https://aur.archlinux.org/paru.git
paru_build_dir: "{{ user_home }}/paru-build"

core_packages:
  - curl
  - wget
  - vim
  - htop
  - zsh
  - unzip
  - rsync
  - mpv
  - kitty
  - fastfetch
  - man-db
  - man-pages

utility_packages:
  - ncdu
  - ripgrep
  - vulkan-tools
  - fuse2
  - fuse3
  - atuin
  - openssl
  - pamixer
  - xdg-utils
  - plocate
  - psmisc
  - github-cli
  - tmux
  - eza
  - bat
  - fd
  - zoxide
  - fzf
  - lazygit
  - git-delta
  - duf
  - procs
  - just
  - trash-cli
  - neovim

media_packages:
  - ffmpeg
  - yt-dlp
  - gimp
  - pavucontrol
  - obs-studio
  - flowblade

office_packages:
  - libreoffice-fresh
  - thunderbird

system_packages:
  - gparted
  - dconf-editor
  - qbittorrent
  - timeshift
  - keepassxc
  - flatpak-builder

fun_packages: []

gaming_packages:
  - steam
  - lutris
  - gamemode
  - mangohud
  - goverlay
  - wine
  - winetricks
  - protontricks
  - piper
  - retroarch

aur_gaming_packages:
  - celeste-classic
  - celeste-classic-pm

dev_packages:
  - git
  - python
  - python-pip
  - python-pipx
  - jq
  - yq
  - httpie
  - ansible-lint
  - yamllint
  - shellcheck
  - pre-commit
  - python-playwright
  - gcc
  - gdb
  - cmake

fonts_packages:
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - ttf-dejavu
  - ttf-liberation
  - gnu-free-fonts

nvidia_packages:
  - nvidia-settings
  - vulkan-icd-loader

virtualization_kvm_packages:
  - qemu-full
  - libvirt
  - virt-install
  - virt-manager
  - bridge-utils
  - edk2-ovmf

virtualization_virtualbox_packages:
  - virtualbox
  - virtualbox-host-modules-arch

libvirt_service: libvirtd
virtualization_user_groups:
  - libvirt
  - kvm

pipewire_packages:
  - pipewire
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - wireplumber
  - gst-plugin-pipewire

bluetooth_packages:
  - bluez
  - bluez-utils

docker_packages:
  - docker
  - docker-compose
  - docker-buildx

docker_group: docker

networking_packages:
  - networkmanager

vpn_packages:
  - wireguard-tools
  - openvpn
  - networkmanager-openvpn

splashboot_packages:
  - plymouth

ssh_package: openssh
ssh_service: sshd

grub_packages_bios:
  - grub

grub_packages_uefi:
  - grub
  - efibootmgr

grub_bootloader_id: GRUB

user_groups:
  - wheel
  - audio
  - video
