---
chezmoi_bin: "{{ user_home }}/.local/bin/chezmoi"
dotfiles_repo_dir: "{{ user_home }}/.local/share/dotfiles"
chezmoi_source_dir: "{{ dotfiles_repo_dir }}/chezmoi"
dotfiles_repo: "https://github.com/Zolkyed/dotfiles.git"
dotfiles_repo_branch: "main"
