---
- name: CPUpower | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: CPUpower
    install_pacman_packages:
      - cpupower

- name: CPUpower | Configure governor
  ansible.builtin.lineinfile:
    path: /etc/default/cpupower
    regexp: '^#?\s*governor='
    line: "governor='{{ cpupower_governor }}'"
    create: true
  notify: CPUpower | Restart service

- name: CPUpower | Enable service
  ansible.builtin.systemd_service:
    name: cpupower
    enabled: true
    state: started
