---
- name: Docker | Configure Debian apt repository
  block:
    - name: Docker | Install repository dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Docker | Create apt keyring directory
      ansible.builtin.file:
        path: "{{ docker_apt_keyring_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Docker | Download official apt repository key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
        dest: "{{ docker_apt_keyring_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Docker | Add Debian apt repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
        suites: "{{ docker_repo_codename | default(ansible_facts['distribution_release']) }}"
        components: stable
        architectures: "{{ ansible_facts['architecture'] | replace('x86_64', 'amd64') }}"
        signed_by: "{{ docker_apt_keyring_path }}"
        state: present
      notify: Docker | Update apt cache

- name: Docker | Flush apt repository handlers
  ansible.builtin.meta: flush_handlers
