---
- name: "Docker | Run Debian tasks"
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts.os_family | lower == "debian"

- name: Docker | Add user to docker group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ profiles.docker.group | default([]) }}"
    append: true

- name: Docker | Enable and start service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
