---
- name: Shell | Install
  ansible.builtin.include_role:
    name: system/install
    tasks_from: packages
  vars:
    install_label: Shell
    install_pacman_packages: "{{ shell_pacman_packages }}"
    install_aur_packages: "{{ shell_aur_packages }}"
