---
- name: Avahi | Ensure mDNS is in hosts resolution
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'
    backup: true

- name: Avahi | Enable and start avahi-daemon
  ansible.builtin.systemd_service:
    name: avahi-daemon
    enabled: true
    state: started
