---
- name: Discord | Download deb package
  ansible.builtin.get_url:
    url: "{{ discord_deb_url }}"
    dest: "{{ discord_deb_dest }}"
    mode: "0644"

- name: Discord | Install deb package
  ansible.builtin.apt:
    deb: "{{ discord_deb_dest }}"
    state: present
