---
# Desktop-specific variables
machine_type: desktop
desktop_environment: kde

# Display
primary_monitor: DP-1

# Bootloader
grub_timeout: 5
grub_cmdline_linux_default: "quiet splash"

# Extra packages (merged with base_packages in system/packages)
extra_packages:
  - mpv
  - kitty
  - fastfetch
