---
dev_pacman_packages:
  - pkgconf
  - python
  - python-pip
  - python-pipx
  - rust
  - jq
  - yq
  - httpie
  - ansible-lint
  - yamllint
  - shellcheck
  - pre-commit
  - python-playwright
  - gcc
  - gdb
  - clang
  - lldb
  - cmake
  - ninja
  - make
  - valgrind

dev_flatpak_packages:
  - com.getpostman.Postman
  - net.portswigger.BurpSuite-Community
