---
- name: Pacman | Check enabled repositories
  ansible.builtin.command:
    cmd: pacman-conf --repo-list
  register: pacman_repositories
  changed_when: false

- name: Pacman | Set ParallelDownloads
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: ^ParallelDownloads
    line: ParallelDownloads = 5
    insertafter: ^\[options\]
  notify: Pacman | Update pacman cache

- name: Pacman | Enable Color
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: ^Color
    line: Color
    insertafter: ^\[options\]
  notify: Pacman | Update pacman cache

- name: Pacman | Enable ILoveCandy
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: ^ILoveCandy
    line: ILoveCandy
    insertafter: ^\[options\]
  notify: Pacman | Update pacman cache

- name: Pacman | Enable VerbosePkgLists
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: ^VerbosePkgLists
    line: VerbosePkgLists
    insertafter: ^\[options\]
  notify: Pacman | Update pacman cache

- name: Pacman | Enable multilib repository
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE MANAGED MULTILIB"
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  notify: Pacman | Update pacman cache
  when:
    - pacman_enable_multilib
    - "'multilib' not in pacman_repositories.stdout_lines"

- name: Pacman | Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Pacman | Update Arch Linux keyring
  community.general.pacman:
    name: archlinux-keyring
    state: latest
    update_cache: true

- name: Pacman | Full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Pacman | Ensure hooks directory exists
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Pacman | Deploy paccache cleanup hook
  ansible.builtin.copy:
    dest: /etc/pacman.d/hooks/paccache.hook
    owner: root
    group: root
    mode: "0644"
    content: |
      [Trigger]
      Operation = Upgrade
      Operation = Install
      Operation = Remove
      Type = Package
      Target = *

      [Action]
      Description = Cleaning pacman cache (keeping last 2 versions)...
      When = PostTransaction
      Exec = /usr/bin/paccache -rk2
