---
- name: Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ bin_dest }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Install custom scripts to ~/.local/bin
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bin_dest }}/{{ item | basename }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  with_fileglob:
    - "{{ role_path }}/files/*"
