---
- name: Rclone | Run Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: Rclone | Run Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure rclone config directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/rclone"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Deploy rclone config
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ apps_rclone_conf_dest }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
  no_log: true
