---
- name: "Rclone | Run tasks for {{ ansible_facts.os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Rclone | Ensure config directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/rclone"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Rclone | Deploy config
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ rclone_conf_dest }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
  no_log: true
