---
- name: Gaming | Configure Arch multilib support
  when: "'steam' in (profiles.gaming.pacman | default([]))"
  block:
    - name: Gaming | Check Arch pacman repositories
      ansible.builtin.command:
        cmd: pacman-conf --repo-list
      register: arch_pacman_repositories
      changed_when: false

    - name: Gaming | Enable Arch multilib repository for Steam
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        marker: "# {mark} ANSIBLE MANAGED MULTILIB"
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
      notify: Gaming | Update pacman cache
      when: "'multilib' not in arch_pacman_repositories.stdout_lines"

- name: Gaming | Flush repository handlers
  ansible.builtin.meta: flush_handlers
