---
- name: Gaming | Configure Arch multilib support
  when: "'steam' in pacman_packages.gaming"
  block:
    - name: Gaming | Check Arch pacman repositories
      ansible.builtin.command:
        cmd: pacman-conf --repo-list
      register: arch_pacman_repositories
      changed_when: false

    - name: Gaming | Enable Arch multilib repository for Steam
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        marker: "# {mark} ANSIBLE MANAGED MULTILIB"
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
      notify: Gaming | Update pacman cache
      when: "'multilib' not in arch_pacman_repositories.stdout_lines"

- name: Gaming | Flush repository handlers
  ansible.builtin.meta: flush_handlers

- name: Gaming | Install packages
  community.general.pacman:
    name: "{{ pacman_packages.gaming }}"
    state: present
  when: pacman_packages.gaming | length > 0
