---
- name: Gaming | Configure Debian i386 support
  when:
    - >
      ('steam' in (profiles.gaming.apt | default([]))) or
      ('wine' in (profiles.gaming.apt | default([]))) or
      ('winetricks' in (profiles.gaming.apt | default([])))
  block:
    - name: Gaming | Check Debian foreign architectures
      ansible.builtin.command:
        cmd: dpkg --print-foreign-architectures
      register: gaming_debian_foreign_architectures
      changed_when: false

    - name: Gaming | Enable Debian i386 architecture
      ansible.builtin.command:
        cmd: dpkg --add-architecture i386
      changed_when: true
      notify: Gaming | Update apt cache
      when: "'i386' not in gaming_debian_foreign_architectures.stdout_lines"

- name: Gaming | Flush repository handlers
  ansible.builtin.meta: flush_handlers
