---
- name: Gaming | Configure Debian i386 support
  when:
    - >
      ('steam' in apps_gaming_packages) or
      ('wine' in apps_gaming_packages) or
      ('winetricks' in apps_gaming_packages)
  block:
    - name: Gaming | Check Debian foreign architectures
      ansible.builtin.command:
        cmd: dpkg --print-foreign-architectures
      register: apps_gaming_debian_foreign_architectures
      changed_when: false

    - name: Gaming | Enable Debian i386 architecture
      ansible.builtin.command:
        cmd: dpkg --add-architecture i386
      changed_when: true
      notify: Gaming | Update apt cache
      when: "'i386' not in apps_gaming_debian_foreign_architectures.stdout_lines"

- name: Gaming | Install packages
  ansible.builtin.apt:
    name: "{{ apps_gaming_packages }}"
    state: present
