---
- name: Gaming | Configure Debian i386 support
  when:
    - >
      ('steam' in gaming_packages) or
      ('wine' in gaming_packages) or
      ('winetricks' in gaming_packages)
  block:
    - name: Gaming | Check Debian foreign architectures
      ansible.builtin.command:
        cmd: dpkg --print-foreign-architectures
      register: gaming_debian_foreign_architectures
      changed_when: false

    - name: Gaming | Enable Debian i386 architecture
      ansible.builtin.command:
        cmd: dpkg --add-architecture i386
      changed_when: true
      notify: Gaming | Update apt cache
      when: "'i386' not in gaming_debian_foreign_architectures.stdout_lines"

- name: Gaming | Flush repository handlers
  ansible.builtin.meta: flush_handlers

- name: Gaming | Install packages
  ansible.builtin.apt:
    name: "{{ gaming_packages }}"
    state: present
  when: gaming_packages | length > 0
