---
- name: "Gaming | Run {{ ansible_facts.os_family }} tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Gaming | Flush repository handlers
  ansible.builtin.meta: flush_handlers
