---
- name: Gaming | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Gaming
    install_pacman_packages: "{{ gaming_pacman_packages }}"
    install_aur_packages: "{{ gaming_aur_packages }}"
    install_flatpak_packages: "{{ gaming_flatpak_packages }}"

- name: Gaming | Gather user UID for XDG_RUNTIME_DIR
  ansible.builtin.getent:
    database: passwd
    key: "{{ user_name }}"

- name: Gaming | Enable gamemoded user service
  ansible.builtin.systemd_service:
    name: gamemoded
    enabled: true
    scope: user
  become: true
  become_user: "{{ user_name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts.getent_passwd[user_name][1] }}"
