---
- name: Dev | Run Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: Dev | Run Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Dev | Install Rust toolchain
  when: apps_dev_install_rust
  block:
    - name: Dev | Download rustup installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: "0755"

    - name: Dev | Install rustup
      ansible.builtin.command:
        cmd: /tmp/rustup-init.sh -y --no-modify-path
        creates: "{{ user_home }}/.cargo/bin/rustup"
      become: true
      become_user: "{{ user_name }}"

- name: Dev | Install NVM
  when: apps_dev_install_nvm
  block:
    - name: Dev | Download nvm installer
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ apps_dev_nvm_version }}/install.sh"
        dest: "/tmp/nvm-install-{{ apps_dev_nvm_version }}.sh"
        mode: "0755"

    - name: Dev | Install nvm
      ansible.builtin.command:
        cmd: "bash /tmp/nvm-install-{{ apps_dev_nvm_version }}.sh"
        creates: "{{ user_home }}/.nvm/nvm.sh"
      become: true
      become_user: "{{ user_name }}"
      environment:
        NVM_DIR: "{{ user_home }}/.nvm"
        PROFILE: /dev/null
