---
- name: Timers | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Timers
    install_pacman_packages: "{{ timers_pacman_packages }}"

- name: Timers | Enable fstrim timer
  ansible.builtin.systemd_service:
    name: fstrim.timer
    enabled: true
    state: started
  when: timers_enable_fstrim

- name: Timers | Enable btrfs scrub timers
  ansible.builtin.systemd_service:
    name: >-
      btrfs-scrub@{{
        '-'
        if item == '/'
        else item | regex_replace('^/', '') | regex_replace('/', '-')
      }}.timer
    enabled: true
    state: started
  loop: "{{ timers_btrfs_scrub_mounts }}"
  when:
    - timers_enable_btrfs_scrub
    - ansible_facts['mounts']
      | selectattr('mount', 'equalto', item)
      | selectattr('fstype', 'equalto', 'btrfs')
      | list
      | length > 0

- name: Timers | Enable pkgfile update timer
  ansible.builtin.systemd_service:
    name: pkgfile-update.timer
    enabled: true
    state: started
  when: timers_enable_pkgfile_update
