---
- name: "Plasma | Run {{ ansible_facts.os_family }} tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Plasma | Deploy KDE keybinds
  ansible.builtin.copy:
    src: "keybinds/{{ inventory_hostname }}.ini"
    dest: "{{ user_home }}/.config/kglobalshortcutsrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
