---
- name: Plasma | Enable SDDM for next boot
  ansible.builtin.systemd_service:
    name: sddm
    enabled: true

- name: Plasma | Deploy KDE keybinds
  ansible.builtin.copy:
    src: "keybinds/{{ inventory_hostname }}.ini"
    dest: "{{ user_home }}/.config/kglobalshortcutsrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"

- name: Plasma | Deploy kcminputrc
  ansible.builtin.copy:
    src: kcminputrc
    dest: "{{ user_home }}/.config/kcminputrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
  when: inventory_hostname == "desktop"
