---
- name: Audio | Enable PipeWire socket globally
  ansible.builtin.systemd:
    name: pipewire.socket
    enabled: true
    scope: global

- name: Audio | Enable PipeWire Pulse socket globally
  ansible.builtin.systemd:
    name: pipewire-pulse.socket
    enabled: true
    scope: global

- name: Audio | Enable WirePlumber service globally
  ansible.builtin.systemd:
    name: wireplumber.service
    enabled: true
    scope: global
