---
- name: Virtualization | Install KVM packages
  community.general.pacman:
    name: "{{ pacman_packages.virtualization_kvm }}"
    state: present
  when:
    - virtualization_backend == "kvm"
    - pacman_packages.virtualization_kvm | length > 0

- name: Virtualization | Install VirtualBox packages
  community.general.pacman:
    name: "{{ pacman_packages.virtualization_virtualbox }}"
    state: present
  when: virtualization_backend == "virtualbox"
