---
- name: Virtualization | Install KVM packages
  ansible.builtin.apt:
    name: "{{ apt_packages.virtualization_kvm }}"
    state: present
  when:
    - virtualization_backend == "kvm"
    - apt_packages.virtualization_kvm | length > 0

- name: Virtualization | Install VirtualBox packages
  ansible.builtin.apt:
    name: "{{ apt_packages.virtualization_virtualbox }}"
    state: present
  when: virtualization_backend == "virtualbox"
