---
- name: Virtualization | Install KVM packages
  ansible.builtin.apt:
    name: "{{ virtualization_kvm_packages }}"
    state: present
  when:
    - virtualization_backend == "kvm"
    - virtualization_kvm_packages | length > 0

- name: Virtualization | Install VirtualBox packages
  ansible.builtin.apt:
    name: "{{ virtualization_virtualbox_packages }}"
    state: present
  when: virtualization_backend == "virtualbox"
