---
- name: "Virtualization | Run {{ ansible_facts.os_family }} tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Enable and start libvirtd
  ansible.builtin.systemd:
    name: "{{ libvirt_service }}"
    enabled: true
    state: started
  when: virtualization_backend == "kvm"

- name: Add user to virtualization groups
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ virtualization_user_groups }}"
    append: true
  when:
    - virtualization_backend == "kvm"
    - virtualization_user_groups | length > 0
