---
- name: Enable and start libvirt services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ profiles.virtualization_kvm.service | default([]) }}"
  when: virtualization_backend == "kvm"

- name: Add user to virtualization groups
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ profiles.virtualization_kvm.group | default([]) }}"
    append: true
  when:
    - virtualization_backend == "kvm"
    - (profiles.virtualization_kvm.group | default([])) | length > 0
