---
- name: User | Collect existing groups
  ansible.builtin.getent:
    database: group

- name: User | Ensure user exists with correct groups
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: "{{ user_shell }}"
    groups: "{{ user_groups | select('in', ansible_facts.getent_group.keys()) | list }}"
    append: true
    state: present

- name: User | Set root shell
  ansible.builtin.user:
    name: root
    shell: "{{ user_shell }}"

- name: User | Ensure user home directory exists
  ansible.builtin.file:
    path: "{{ user_home }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
