---
# Flag overrides
plasma_enabled: false
hyprland_enabled: false
niri_enabled: false
browser_enabled: false
flatpak_enabled: false
hayase_enabled: false
media_enabled: false
office_enabled: false
system_tools_enabled: false
vscode_enabled: false
gaming_enabled: false
konsave_enabled: false
mihon_enabled: false
rclone_enabled: false
xdg_enabled: false
bootloader_enabled: false
splashboot_enabled: false
vpn_enabled: false
