vault_ssh_public_key: ""
vault_ssh_private_key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWHVSSU9vNkhLRFFpM1BM
            WmZ4R1hOcFUxaFFQKzVhYXRkSXEwaW9YVnhjCjA3WnIrMFZEV0RlOExPNkkwZmgx
            cW5rTks4VEdHVWU1elM2bUlLakNQMEUKLS0tIGhoRjQvSWpMUTJZdFF0U1IwTWtR
            L2hEbi9NbFRBY2YxOUx1SlRqUkZGZFUKIRyyB2IJ9pWh06OJ5fGy5hgn/5A9wnzv
            cJTH0SZKCroCby44DGn6IH1jqPuE2RjucCYiaufguFbwe4nNJRSxvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19qvn8ud9na2k04vnf9h0we8zekvqwu8x8q33zte8fhee450xnpwqp8mhvp
    lastmodified: "2026-05-10T01:58:16Z"
    mac: ENC[AES256_GCM,data:bIoRonLs5yz2dpcYaKZ3Z9euqj5qe7ZUt4caNQw2383cktx/Lqc+4z5eW9T5JhKN14x1NFMLeS6ZoQqK0LO725jZ07F8d6a08TvUNfOfouALunmtesxGpRzCsCPXHeOkEhxvg1Z/k9utUPZYlc+aBCxQPCnaR3DOzeC3IbQZuoA=,iv:8ft29JHVCCqto37ZZn8gWwF4N9T/X0WsfaBp6ncW3Uc=,tag:5p8Z6f1LFXxlqrmLl/yMBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
