vault_ssh_public_key: ""
vault_ssh_private_key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdE9ieW4vanpTQWtjWFpZ
            QlFVVzR0SG90T3JabldRdU5SVWx3QklDTGhNCjJUbFQva1ROamduZ1JoV0YzQXJy
            NS9VNi9LNkNjc2lOamp0UGFaOTIxeWMKLS0tIGxGaUdKQUxKUHpzZHdHSkJ6N1E1
            QlNDbEZRSmdOTEFVdGU4VmtKN3VsdXMKrAMcqI/3CiXFgChIAM98g+1YHw08nT3e
            TiKOpUIqpAo6gijMLc76OThsr4beiuFbCjwO4MRxT5RDYd9+f8CUZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19qvn8ud9na2k04vnf9h0we8zekvqwu8x8q33zte8fhee450xnpwqp8mhvp
    lastmodified: "2026-05-09T21:05:42Z"
    mac: ENC[AES256_GCM,data:z9HgKgOSQE9Iyeec+/uwVWvaZ7qZMX+tGBoJXyt0Q+hYqe3aggP0KAKFWeiDNvsM2oarWBZTF2T8Ua1Jl0eZLH7OGvcxy7Xa/M48XPmM7yw5c7wbQcnqzjHpDa7bdm4M02LbP8PAB/vnK6KRjM+meXf4AE86OHD5cZQJ57lqspM=,iv:9dFykihZnMiYhUCeZdJ8Ri5+hsh/AIqLw5J1Vd9LoBE=,tag:B+PCVi/XKr6Aqv2HU7iNcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
