vault_ssh_public_key: ""
vault_ssh_private_key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaXo2MC91TzhCeFcrVDkx
            NDNxMDdPbFhRYkp2WWhmeTM0NWl1bk93c2tnCm0wTVlhZjc5dCszUWQyR0RVRDJo
            WWtBeExUYUFxMTMyalREbUtTSnBtMWsKLS0tIGF2cjNkK0VXZFJvUkRKQkdvU1Nu
            cTY4aUFLamtrdjRBNHplWGswRjIrejgKUML5uHA2hh7qvtjMYn2T1hBD4i4ggPZz
            lzeuqjyz9Ov/kGUcNZ07rP6zs/Dj121j7iCWmzDwEatg6l95NpwZOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19qvn8ud9na2k04vnf9h0we8zekvqwu8x8q33zte8fhee450xnpwqp8mhvp
    lastmodified: "2026-05-14T01:23:42Z"
    mac: ENC[AES256_GCM,data:UhaasCFlqONGsevJF5DJycBawrVi0tv4dULOLZiX7NmcOzwtIjYcU4n4gc5kSdJG/iyyl0f4NUmwXuKXuctOuTLHWY+ctZ8wMP5TDwCFlOpQmDdvq2AZa8vitF/PThswXTpb2/uY6FSDIldWNuqmi6XfspY2dY9hYttDt07xZmU=,iv:rZwvnbqEpkgD7CXaudXidC5zVif+K44iY0h21w6lFVw=,tag:UhFHWXLqysCzKp3nN6GhkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
