---
- name: User | Run Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: User | Run Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure user exists with correct shell and groups
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: "{{ user_shell }}"
    groups: "{{ home_user_groups }}"
    append: true
    state: present

- name: Ensure user home directory exists
  ansible.builtin.file:
    path: "{{ user_home }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
