---
- name: User | Run Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: User | Run Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: User | Collect existing groups
  ansible.builtin.getent:
    database: group

- name: User | Ensure user exists with correct groups
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: "{{ user_shell }}"
    groups: "{{ home_user_groups | select('in', ansible_facts.getent_group.keys()) | list }}"
    append: true
    state: present

- name: User | Ensure user home directory exists
  ansible.builtin.file:
    path: "{{ user_home }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
