---
vscode_aur_packages:
  - visual-studio-code-bin

vscode_extensions:
  - redhat.ansible
  - ms-vscode.cpptools
  - hediet.vscode-drawio
  - eamodio.gitlens
  - oderwat.indent-rainbow
  - wholroyd.jinja
  - ms-python.python
  - ms-pyright.pyright
  - charliermarsh.ruff
  - simonsiefke.svg-preview
  - tomrijndorp.find-it-faster
  - darkphoenix.dark-modern-darker
  - pkief.material-icon-theme
