---
- name: Microcode | Select package
  ansible.builtin.set_fact:
    microcode_package: >-
      {{
        'intel-ucode'
        if ansible_facts.processor | join(' ') is search('GenuineIntel|Intel')
        else 'amd-ucode'
        if ansible_facts.processor | join(' ') is search('AuthenticAMD|AMD')
        else ''
      }}

- name: Microcode | Install CPU microcode
  community.general.pacman:
    name: "{{ microcode_package }}"
    state: present
  when: microcode_package | length > 0
  notify: Microcode | Update grub
