---
- name: Microcode | Install Intel CPU microcode
  community.general.pacman:
    name: intel-ucode
    state: present
  when: ansible_facts.processor | join(' ') is search('GenuineIntel|Intel')
  notify: Bootloader | Update grub

- name: Microcode | Install AMD CPU microcode
  community.general.pacman:
    name: amd-ucode
    state: present
  when: ansible_facts.processor | join(' ') is search('AuthenticAMD|AMD')
  notify: Bootloader | Update grub
