---
- name: Install PipeWire packages
  ansible.builtin.package:
    name: "{{ pipewire_packages }}"
    state: present

- name: Enable and start PipeWire services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: "{{ pipewire_enabled }}"
    state: "{{ 'started' if pipewire_enabled else 'stopped' }}"
    scope: user
  become: true
  become_user: "{{ user_name }}"
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber
