---
networking_hostname: "{{ inventory_hostname }}"

networking_pacman_packages:
  - networkmanager

networking_dns_servers:
  - "1.1.1.1"
  - "9.9.9.9"
networking_dns_fallback_servers:
  - "8.8.8.8"
networking_dns_dnssec: "allow-downgrade"
networking_dns_over_tls: "opportunistic"
