# tasks/main.yml
---
- name: Apply KDE config settings
  community.general.kdeconfig:
    path: "{{ item.file if item.file | is_abs
              else (user_home + '/.config/' + item.file) }}"
    kwriteconfig_path: "/usr/bin/kwriteconfig{{ kde_config_version }}"
    values:
      - group: "{{ item.group }}"
        key: "{{ item.key }}"
        value: "{{ item.value | default(omit) }}"
        bool_value: "{{ item.bool_value | default(omit) }}"
  loop: "{{ kde_settings }}"
  loop_control:
    label: "{{ item.file }}::{{ item.group }}/{{ item.key }}"
  become: true
  become_user: "{{ user_name }}"
  when: kde_settings | length > 0