include themes/burzum.conf

# Fonts

font_family      BlexMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

disable_ligatures never

# Mouse and Urls

detect_urls yes
copy_on_select clipboard

# Terminal bell 

enable_audio_bell no

# Window padding

window_padding_width 15
