---
kernel_sysctl_file: /etc/sysctl.d/99-local.conf
kernel_sysctl_settings:
  vm.swappiness: 10
  fs.inotify.max_user_watches: 524288
  fs.inotify.max_user_instances: 512

kernel_pacman_packages:
  - linux-zen
  - linux-zen-headers
