---
system_btrfs_manage_packages: true
system_btrfs_packages: []

system_btrfs_subvolumes: []
# - path: /mnt/btrfs/@
#   owner: root
#   group: root
#   mode: "0755"

system_btrfs_mounts: []
# - src: UUID=xxxx
#   path: /home
#   fstype: btrfs
#   opts:
#     - subvol=@home
#     - compress=zstd:3
#     - noatime
#     - ssd
#   dump: "0"
#   passno: "0"
#   state: mounted

system_btrfs_enable_scrub_timer: true
system_btrfs_scrub_timer: btrfs-scrub@-.timer

system_btrfs_enable_balance_timer: false
system_btrfs_balance_timer: btrfs-balance.timer

system_btrfs_enable_quotas: false
system_btrfs_quota_mountpoint: /
