---
maintenance_pacman_packages:
  - btrfs-progs
  - pkgfile
  - dosfstools

maintenance_enable_fstrim: true
maintenance_enable_btrfs_scrub: true
maintenance_btrfs_scrub_mounts:
  - /
  - /home
maintenance_enable_pkgfile_update: true
