---
extra_apt_repos:
  - name: brave-browser
    gpg_url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    gpg_dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    uri: https://brave-browser-apt-release.s3.brave.com/
    suite: stable
    components: main
    packages:
      - brave-browser

  - name: cloudflare-warp
    gpg_url: https://pkg.cloudflareclient.com/pubkey.gpg
    gpg_dest: /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
    uri: https://pkg.cloudflareclient.com/
    suite: noble
    components: main
    packages:
      - cloudflare-warp

  - name: github-cli
    gpg_url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    gpg_dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    uri: https://cli.github.com/packages
    suite: stable
    components: main
    packages:
      - gh

  - name: vscode
    gpg_url: https://packages.microsoft.com/keys/microsoft.asc
    gpg_dest: /usr/share/keyrings/microsoft-archive-keyring.gpg
    uri: https://packages.microsoft.com/repos/code
    suite: stable
    components: main
    packages:
      - code

  - name: 1password
    gpg_url: https://downloads.1password.com/linux/keys/1password.asc
    gpg_dest: /usr/share/keyrings/1password-archive-keyring.gpg
    uri: https://downloads.1password.com/linux/debian/amd64
    suite: stable
    components: main
    packages:
      - 1password
      - 1password-cli

  - name: signal
    gpg_url: https://updates.signal.org/desktop/apt/keys.asc
    gpg_dest: /usr/share/keyrings/signal-desktop-keyring.gpg
    uri: https://updates.signal.org/desktop/apt
    suite: xenial
    components: main
    packages:
      - signal-desktop

  - name: spotify
    gpg_url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    gpg_dest: /usr/share/keyrings/spotify-archive-keyring.gpg
    uri: http://repository.spotify.com
    suite: stable
    components: non-free
    packages:
      - spotify-client

  - name: tailscale
    gpg_url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
    gpg_dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    uri: https://pkgs.tailscale.com/stable/ubuntu/noble
    suite: tailscale-stable
    components: main
    packages:
      - tailscale

  - name: syncthing
    gpg_url: https://syncthing.net/release-key.gpg
    gpg_dest: /usr/share/keyrings/syncthing-archive-keyring.gpg
    uri: https://apt.syncthing.net/
    suite: syncthing
    components: stable
    packages:
      - syncthing

