---
bootloader_pacman_packages:
  - grub
  - efibootmgr
  - grub-theme-vimix

bootloader_aur_packages:
  - grub-hook

bootloader_grub_timeout: 1
bootloader_grub_timeout_style: hidden
bootloader_grub_cmdline_linux_default: "quiet"
bootloader_grub_gfxmode: "auto"
bootloader_grub_disable_os_prober: true
bootloader_grub_theme: "/usr/share/grub/themes/Vimix/theme.txt"
