---
system_grub_timeout: 5
system_grub_cmdline_linux_default: "quiet splash"
system_grub_cmdline_linux: ""
system_grub_gfxmode: "auto"
system_grub_efi_directory: /boot/efi
system_grub_bootloader_id: "GRUB"
system_grub_efi_target: "x86_64-efi"
system_grub_packages_bios: []
system_grub_packages_uefi: []
