---
- name: AUR | Check installed packages
  ansible.builtin.command:
    cmd: "pacman -Q {{ item }}"
  loop: "{{ system_aur_install_packages }}"
  register: system_aur_install_package_checks
  changed_when: false
  failed_when: false

- name: AUR | Install missing packages
  ansible.builtin.command:
    argv:
      - paru
      - -S
      - --needed
      - --noconfirm
      - --skipreview
      - "{{ system_aur_install_package_check.item }}"
  become: true
  become_user: "{{ user_name }}"
  loop: "{{ system_aur_install_package_checks.results | default([]) }}"
  loop_control:
    loop_var: system_aur_install_package_check
    label: "{{ system_aur_install_package_check.item }}"
  when: system_aur_install_package_check.rc != 0
