---
- name: AUR | Update pacman cache
  community.general.pacman:
    update_cache: true

- name: AUR | Install build packages
  community.general.pacman:
    name: "{{ aur_build_packages }}"
    state: present
  when: aur_build_packages | length > 0

- name: AUR | Install packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    use: makepkg
    state: present
  become: true
  become_user: "{{ user_name }}"
  when: aur_packages | length > 0
