---
- name: Intel GPU | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Intel GPU
    install_pacman_packages: "{{ intel_gpu_pacman_packages }}"
