---
kde_packages:
  - plasma-desktop
  - plasma-workspace
  - konsole
  - dolphin
  - kate
  - kde-spectacle
  - ark
  - plasma-nm
  - plasma-pa
  - powerdevil
  - bluedevil
  - kscreen
  - sddm
  - sddm-theme-breeze
  - kde-standard
  - kde-cli-tools
  - breeze-cursor-theme
kde_managed_assets: []
kde_config_files:
  - path: "{{ user_home }}/.config/kdeglobals"
    values:
      - group: General
        key: ColorScheme
        value: DreamVioletDarkColor
      - group: Icons
        key: Theme
        value: Tela-black
      - group: General
        key: font
        value: Noto Sans,10,-1,5,50,0,0,0,0,0
      - group: General
        key: fixed
        value: DejaVu Sans Mono,11,-1,5,50,0,0,0,0,0
  - path: "{{ user_home }}/.config/kcminputrc"
    values:
      - group: Mouse
        key: cursorTheme
        value: breeze
      - group: Mouse
        key: cursorSize
        value: "24"
