---
- name: Fonts | Run Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: Fonts | Run Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Create Nerd Fonts install directory
  ansible.builtin.file:
    path: "{{ system_nerd_fonts_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Nerd Fonts archives
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ system_fonts_nerd.version }}/{{ item }}.tar.xz"
    dest: "/tmp/{{ item }}.tar.xz"
    mode: "0644"
  loop: "{{ system_fonts_nerd.families }}"
  register: system_nerd_fonts_download
  when: system_fonts_nerd.version | length > 0
  notify: Extract Nerd Fonts
