---
- name: "Fonts | Run {{ ansible_facts.os_family }} tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Fonts | Create Nerd Fonts install directory
  ansible.builtin.file:
    path: "{{ fonts_nerd_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Fonts | Download Nerd Fonts archives
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ fonts_nerd.version }}/{{ item }}.tar.xz"
    dest: "/tmp/{{ item }}.tar.xz"
    mode: "0644"
  loop: "{{ fonts_nerd.families }}"
  register: fonts_nerd_download
  when: fonts_nerd.version | length > 0
  notify: Fonts | Extract Nerd Fonts
