---
home_browser_policy_dir: /etc/brave/policies/managed
home_browser_policy_file: zz-browser-policy.json
home_browser_extensions:
  - name: Bitwarden
    id: nngceckbapebfimnlniiiahkandclblb
    update_url: https://clients2.google.com/service/update2/crx
  - name: Smooth Key Scroll
    id: gphmhpfbknciemgfnfhjapilmcaecljh
    update_url: https://clients2.google.com/service/update2/crx
  - name: Stylus
    id: clngdbkpkpeebahjckkjfobafhncgmne
    update_url: https://clients2.google.com/service/update2/crx
  - name: Animouto
    id: ilhjhegbgdghfkdgeahkpikkjgaaoklh
    update_url: https://clients2.google.com/service/update2/crx
  - name: Violentmonkey
    id: jinjaccalgkegednnccohejagnlnfdag
    update_url: https://clients2.google.com/service/update2/crx
home_browser_extra_policies: {}
