---
- name: SSH Keys | Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: SSH Keys | Deploy SSH private keys
  ansible.builtin.copy:
    content: "{{ item.private_key | trim }}\n"
    dest: "{{ user_home }}/.ssh/{{ item.name }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
  loop: "{{ ssh_keys_list }}"
  when: item.private_key != ''
  no_log: true

- name: SSH Keys | Deploy SSH public keys
  ansible.builtin.copy:
    content: "{{ item.public_key }}"
    dest: "{{ user_home }}/.ssh/{{ item.name }}.pub"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
  loop: "{{ ssh_keys_list }}"
  when: item.public_key != ''
  no_log: true
