---
- name: Splashboot | Run Debian handlers
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"
  listen: Splashboot | Update initramfs

- name: Splashboot | Run Arch Linux handlers
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"
  listen: Splashboot | Update initramfs
