---
- name: Apply dotfiles
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Dotfiles | Apply via chezmoi
      ansible.builtin.command:
        cmd: chezmoi apply --no-tty --force --exclude scripts
      changed_when: false
