---
- name: Full system setup
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Load shared secrets
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/../inventory/group_vars/vault.yml"
      become: false

    - name: Load host secrets
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/../inventory/host_vars/{{ inventory_hostname }}/vault.yml"
      become: false

    - name: Load distro-specific vars
      tags: always
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../vars/{{ ansible_facts['os_family'] }}.yml"

  roles:
    - role: home/packages
    - role: home/hayase
    - role: home/user
    - role: system/fonts
    - role: system/flatpak
    - role: system/docker
    - role: system/nvidia
      when: machine_type == "desktop"
    - role: system/vm
    - role: home/dotfiles
    - role: home/ssh_keys
    - role: home/dev
    - role: home/bin
    - role: system/networking
    - role: system/ssh
    - role: system/bluetooth
    - role: system/bootloader
    - role: system/display_manager
    - role: desktop/kde/rclone
    - role: desktop/kde/konsave
    - role: desktop/kde/keybinds
    - role: home/gaming
      when: machine_type == "desktop"
