---
- name: Snapper | Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Snapper | Check stale /home/.snapshots
  ansible.builtin.stat:
    path: /home/.snapshots
  register: snapper_home_snapshots

- name: Snapper | Remove stale /home/.snapshots if needed
  ansible.builtin.command:
    cmd: btrfs subvolume delete /home/.snapshots
    creates: /etc/snapper/configs/home
  when: snapper_home_snapshots.stat.exists

- name: Snapper | Create snapper configs
  ansible.builtin.command:
    cmd: "snapper -c {{ item.config }} create-config {{ item.path }}"
    creates: "/etc/snapper/configs/{{ item.config }}"
  loop: "{{ snapper_subvolumes }}"

- name: Snapper | Ensure .snapshots directories exist
  ansible.builtin.file:
    path: "{{ item.path }}/.snapshots"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ snapper_subvolumes }}"

- name: Snapper | Configure snapper retention
  ansible.builtin.lineinfile:
    path: "/etc/snapper/configs/{{ item[0].config }}"
    regexp: "^{{ item[1].key }}"
    line: "{{ item[1].key }}={{ item[1].value }}"
  loop: "{{ snapper_subvolumes | product(snapper_retention_settings) }}"
  vars:
    snapper_retention_settings:
      - key: TIMELINE_CREATE
        value: "yes"
      - key: ALLOW_USERS
        value: "{{ user_name }}"
      - key: TIMELINE_LIMIT_HOURLY
        value: "{{ snapper_timeline_limit.hourly }}"
      - key: TIMELINE_LIMIT_DAILY
        value: "{{ snapper_timeline_limit.daily }}"
      - key: TIMELINE_LIMIT_WEEKLY
        value: "{{ snapper_timeline_limit.weekly }}"
      - key: TIMELINE_LIMIT_MONTHLY
        value: "{{ snapper_timeline_limit.monthly }}"
      - key: CLEANUP_ALGORITHM
        value: "{{ snapper_cleanup_algorithm }}"

- name: Snapper | Enable and start grub-btrfsd
  ansible.builtin.systemd_service:
    name: grub-btrfsd
    enabled: true
    state: started

- name: Snapper | Enable and start snapper timers
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - snapper-timeline.timer
    - snapper-cleanup.timer
