---
- name: NPM | Setup global tools
  vars:
    npm_packages: >-
      {{
        package_profiles
        | map('extract', profiles)
        | map(attribute='npm', default=[])
        | flatten
        | unique
      }}
  when: npm_packages | length > 0
  block:
    - name: NPM | Install Volta
      kewlfft.aur.aur:
        name: volta-bin
        use: paru
        state: present
      become: false

    - name: NPM | Install Node LTS with Volta
      ansible.builtin.command:
        cmd: volta install node@lts
      become: true
      become_user: "{{ user_name }}"
      environment:
        VOLTA_HOME: "{{ user_home }}/.volta"
        PATH: "{{ user_home }}/.volta/bin:{{ ansible_facts.env.PATH }}"
      changed_when: false

    - name: NPM | Install global tools with Volta
      ansible.builtin.command:
        cmd: volta install {{ item }}
      become: true
      become_user: "{{ user_name }}"
      environment:
        VOLTA_HOME: "{{ user_home }}/.volta"
        PATH: "{{ user_home }}/.volta/bin:{{ ansible_facts.env.PATH }}"
      loop: "{{ npm_packages }}"
      changed_when: false
