---
# Custom scripts deployed to ~/.local/bin
# Add scripts to roles/home/user/bin/files/ and they will be installed automatically
bin_dest: "{{ user_home }}/.local/bin"

webhookUrl: "https://trigger.macrodroid.com/98a1a60c-632c-47ca-b33e-7e40ad3f23ab/findPhone"
baseUrl: "https://home.mihon.org"
entityIDFan: "switch.charles_fan"
entityIDLight: "light.charles_light"