---
- name: Pipx | Setup Python CLI tools
  vars:
    pipx_packages: >-
      {{
        package_profiles
        | map('extract', profiles)
        | map(attribute='pipx', default=[])
        | flatten
        | unique
      }}
  when: pipx_packages | length > 0
  block:
    - name: Pipx | Install package manager
      community.general.pacman:
        name: python-pipx
        state: present

    - name: Pipx | Install CLI tools
      community.general.pipx:
        name: "{{ item }}"
        state: present
        executable: /usr/bin/pipx
      become: true
      become_user: "{{ user_name }}"
      loop: "{{ pipx_packages }}"
