---
- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add flatpak remotes
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.url }}"
    state: present
  loop: "{{ home_flatpak_remotes }}"

- name: Install flatpak apps
  community.general.flatpak:
    name: "{{ home_flatpak_apps }}"
    state: present
    remote: flathub
  vars:
    home_flatpak_apps: >-
      {{
        home_shared_flatpaks +
        home_distro_flatpaks +
        (gaming_enabled | ternary(home_gaming_flatpaks, []))
      }}
  when:
    - home_flatpak_apps | length > 0
