---
firewall_pacman_packages:
  - ufw

firewall_kde_connect_ports: "1714:1764"

firewall_allow_ports:
  - "{{ ssh_port }}"
  - "{{ firewall_kde_connect_ports }}"

firewall_allow_ports_udp:
  - "{{ firewall_kde_connect_ports }}"

firewall_default_incoming: deny
firewall_default_outgoing: allow
