---
- name: Browser | Install Arch package from AUR  # noqa var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: system/aur
    tasks_from: install_packages
  vars:
    system_aur_install_packages:
      - "{{ apps_browser_arch_package }}"
