---
- name: Browser | Configure Debian apt repository
  block:
    - name: Browser | Install Debian repository dependencies
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Browser | Download Brave apt keyring
      ansible.builtin.get_url:
        url: "{{ browser_debian_keyring_url }}"
        dest: "{{ browser_debian_keyring_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Browser | Download Brave apt sources
      ansible.builtin.get_url:
        url: "{{ browser_debian_sources_url }}"
        dest: "{{ browser_debian_sources_path }}"
        owner: root
        group: root
        mode: "0644"
      notify: Browser | Update apt cache

- name: Browser | Flush repository handlers
  ansible.builtin.meta: flush_handlers

- name: Browser | Install Debian package
  ansible.builtin.apt:
    name: "{{ profiles.browser.package }}"
    state: present
