---
- name: VPN | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: VPN
    install_pacman_packages: "{{ vpn_pacman_packages }}"
    install_aur_packages: "{{ vpn_aur_packages }}"
