---
- name: Packages | Install packages
  community.general.pacman:
    name: "{{
      pacman_packages.core +
      pacman_packages.utility +
      pacman_packages.fun +
      (office_enabled | ternary(pacman_packages.office | default([]), [])) +
      (system_tools_enabled | ternary(pacman_packages.system_tools | default([]), []))
    }}"
    state: present

- name: Packages | Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages | dict2items | map(attribute='value') | flatten }}"
    use: paru
    state: present
  become: true
  become_user: "{{ user_name }}"
  when: aur_packages | dict2items | map(attribute='value') | flatten | length > 0
