---
- name: Packages | Install packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{
      apt_packages.core +
      apt_packages.utility +
      apt_packages.fun +
      (office_enabled | ternary(apt_packages.office | default([]), [])) +
      (system_tools_enabled | ternary(apt_packages.system_tools | default([]), []))
    }}"
    state: present
