---
- name: Packages | Install packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{
      core_packages +
      utility_packages +
      fun_packages +
      (office_enabled | ternary(office_packages | default([]), [])) +
      (system_tools_enabled | ternary(system_tools_packages | default([]), []))
    }}"
    state: present
