---
- name: Packages | Install pacman packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present
    extra_args: >-
      {{
        '--ask 4'
        if pacman_packages | intersect(packages_pacman_conflict_resolvers) | length > 0
        else omit
      }}
  when: pacman_packages | length > 0
  register: packages_pacman_install
  until: packages_pacman_install is succeeded
  retries: "{{ packages_pacman_install_retries }}"
  delay: "{{ packages_pacman_install_delay }}"
  vars:
    pacman_packages: >-
      {{
        package_profiles
        | map('extract', profiles)
        | map(attribute='pacman', default=[])
        | flatten
        | unique
      }}

- name: Packages | Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    use: paru
    state: present
    extra_args: >-
      {{
        '--ask 4'
        if aur_packages | intersect(packages_aur_conflict_resolvers) | length > 0
        else omit
      }}
  become: false
  when: aur_packages | length > 0
  register: packages_aur_install
  until: packages_aur_install is succeeded
  retries: "{{ packages_aur_install_retries }}"
  delay: "{{ packages_aur_install_delay }}"
  vars:
    aur_packages: >-
      {{
        package_profiles
        | map('extract', profiles)
        | map(attribute='aur', default=[])
        | flatten
        | unique
      }}
