---
- name: Packages | Install pacman packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present
  when: pacman_packages | length > 0
  vars:
    pacman_packages: >-
      {{
        package_profiles
        | map('extract', profiles)
        | map(attribute='pacman', default=[])
        | flatten
        | unique
      }}

- name: Packages | Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    use: paru
    state: present
  become: true
  become_user: "{{ user_name }}"
  become_method: community.general.su
  become_exe: runuser
  when: aur_packages | length > 0
  vars:
    aur_packages: >-
      {{
        package_profiles
        | map('extract', profiles)
        | map(attribute='aur', default=[])
        | flatten
        | unique
      }}
