---
- name: Dotfiles | Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ user_home }}/.local/bin"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Dotfiles | Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Dotfiles | Manage as user
  become: true
  become_user: "{{ user_name }}"
  block:
    - name: Dotfiles | Install chezmoi
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "{{ user_home }}/.local/bin"
        creates: "{{ chezmoi_bin }}"

    - name: Dotfiles | Check if dotfiles repo is initialized
      ansible.builtin.stat:
        path: "{{ dotfiles_repo_dir }}/.git"
      register: dotfiles_git

    - name: Dotfiles | Remove non-git dotfiles dir to allow fresh clone
      ansible.builtin.file:
        path: "{{ dotfiles_repo_dir }}"
        state: absent
      when: not dotfiles_git.stat.exists

    - name: Dotfiles | Clone/pull dotfiles repo
      ansible.builtin.git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_repo_dir }}"
        version: "{{ dotfiles_repo_branch }}"
        update: true

    - name: Dotfiles | Apply dotfiles
      ansible.builtin.command:
        cmd: "{{ chezmoi_bin }} apply --source {{ chezmoi_source_dir }} --no-tty --force --exclude scripts"
      register: chezmoi_apply
      changed_when: chezmoi_apply.stdout != ""
