---
niri_packages:
  - niri
  - xdg-desktop-portal-wlr
  - waybar
  - kitty
  - rofi
  - mako
  - swaylock
  - swayidle
  - wl-clipboard
  - grim
  - slurp
  - brightnessctl
  - playerctl
  - network-manager-applet
  - pavucontrol
