---
- name: Install packages
  ansible.builtin.package:
    name: "{{
      home_core_packages +
      home_utility_packages +
      home_media_packages +
      home_office_packages +
      home_system_packages +
      home_fun_packages
    }}"
    state: present
