---
- name: Packages | Run Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: Packages | Run Arch Linux tasks
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"
