---
- name: Hyprland | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Hyprland
    install_pacman_packages: "{{ hyprland_pacman_packages }}"
