---
- name: Node | Install
  ansible.builtin.include_role:
    name: system/install
    tasks_from: packages
  vars:
    install_label: Node
    install_aur_packages: "{{ node_aur_packages }}"

- name: Node | Install Node LTS
  ansible.builtin.command:
    cmd: volta install node@lts
  become: true
  become_user: "{{ user_name }}"
  environment:
    VOLTA_HOME: "{{ user_home }}/.volta"
    PATH: "{{ user_home }}/.volta/bin:{{ ansible_facts.env.PATH }}"
  changed_when: false
