---
- name: Networking | Set hostname
  ansible.builtin.hostname:
    name: "{{ networking_hostname }}"

- name: Networking | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Networking
    install_pacman_packages: "{{ networking_pacman_packages }}"

- name: Networking | Deploy systemd-resolved configuration
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  notify: Networking | Restart systemd-resolved

- name: Networking | Enable and start systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: true
    state: started

- name: Networking | Enable and start NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager
    enabled: true
    state: started

- name: Networking | Symlink resolv.conf to systemd-resolved stub
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
    owner: root
    group: root
