---
- name: Bluetooth | Auto-enable adapters
  community.general.ini_file:
    path: /etc/bluetooth/main.conf
    section: Policy
    option: AutoEnable
    value: "true"
    state: present
    owner: root
    group: root
    mode: "0644"
  notify: Bluetooth | Restart bluetooth

- name: Bluetooth | Enable and start bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
    state: started
