---
snapper_pacman_packages:
  - snapper
  - snap-pac
  - grub-btrfs
  - inotify-tools

snapper_timeline_limit:
  hourly: 6
  daily: 7
  weekly: 4
  monthly: 3
snapper_cleanup_algorithm: "timeline"
snapper_subvolumes:
  - path: "/"
    config: root
  - path: "/home"
    config: home
