---
system_snapper_manage_packages: true
system_snapper_packages: []

system_snapper_configs:
  - name: root
    filesystem_root: /
    allow_users: []
    allow_groups: []
    sync_acl: false
    timeline_create: true
    timeline_cleanup: true
    number_cleanup: true
    number_limit: "50"
    number_limit_important: "10"
    timeline_limit_hourly: "10"
    timeline_limit_daily: "7"
    timeline_limit_weekly: "4"
    timeline_limit_monthly: "6"
    timeline_limit_yearly: "1"

system_snapper_enable_timeline_timer: true
system_snapper_timeline_timer: snapper-timeline.timer

system_snapper_enable_cleanup_timer: true
system_snapper_cleanup_timer: snapper-cleanup.timer
