---
- name: VSCode | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: VSCode
    install_aur_packages: "{{ vscode_aur_packages }}"

- name: VSCode | Install extensions
  ansible.builtin.command:
    argv:
      - code
      - --install-extension
      - "{{ item }}"
  loop: "{{ vscode_extensions }}"
  loop_control:
    label: "{{ item }}"
  register: vscode_extension_result
  retries: 3
  delay: 3
  until: vscode_extension_result.rc == 0
  changed_when: >
    'is already installed' not in vscode_extension_result.stdout
  become: false
