---
- name: NTP | Configure systemd-timesyncd
  ansible.builtin.copy:
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Time]
      NTP={{ ntp_servers | join(' ') }}
      FallbackNTP={{ ntp_fallback_servers | join(' ') }}

- name: NTP | Enable and start systemd-timesyncd
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    enabled: true
    state: started
