---
- name: Maintenance | Enable fstrim timer
  ansible.builtin.systemd_service:
    name: fstrim.timer
    enabled: true
    state: started
  when: maintenance_enable_fstrim

- name: Maintenance | Enable btrfs scrub timers
  ansible.builtin.systemd_service:
    name: >-
      btrfs-scrub@{{
        '-'
        if item == '/'
        else item | regex_replace('^/', '') | regex_replace('/', '-')
      }}.timer
    enabled: true
    state: started
  loop: "{{ maintenance_btrfs_scrub_mounts }}"
  when:
    - maintenance_enable_btrfs_scrub
    - ansible_facts['mounts']
      | selectattr('mount', 'equalto', item)
      | selectattr('fstype', 'equalto', 'btrfs')
      | list
      | length > 0

- name: Maintenance | Enable pkgfile update timer
  ansible.builtin.systemd_service:
    name: pkgfile-update.timer
    enabled: true
    state: started
  when: maintenance_enable_pkgfile_update
