---
plasma_pacman_packages:
  # Core
  - plasma-desktop
  - sddm
  - sddm-kcm

  # Session and portals
  - xdg-desktop-portal
  - xdg-desktop-portal-kde

  # Plasma components
  - plasma-pa
  - plasma-nm
  - kscreen
  - powerdevil
  - bluedevil
  - plasma-systemmonitor

  # Apps
  - discover
  - dolphin
  - spectacle
  - kcalc
  - ark
  - kdeconnect
  - wl-clipboard

  # Thumbnails and formats
  - ffmpegthumbs
  - kdegraphics-thumbnailers
  - kimageformats

  # Integration
  - breeze-gtk

  # Filesystem
  - gvfs
  - gvfs-mtp
  - gvfs-smb
