---
xdg_browser_desktop: brave-browser.desktop
xdg_editor_desktop: code.desktop
xdg_file_manager_desktop: org.kde.dolphin.desktop
xdg_mail_desktop: thunderbird.desktop
xdg_media_player_desktop: mpv.desktop
xdg_terminal_desktop: kitty.desktop
xdg_terminal_command: kitty

xdg_browser_mime_types:
  - text/html
  - x-scheme-handler/http
  - x-scheme-handler/https

xdg_editor_mime_types:
  - text/plain
  - application/json
  - application/x-shellscript
  - text/markdown
  - text/x-python

xdg_file_manager_mime_types:
  - inode/directory

xdg_mail_mime_types:
  - message/rfc822
  - x-scheme-handler/mailto

xdg_pdf_desktop: brave-browser.desktop

xdg_pdf_mime_types:
  - application/pdf

xdg_media_mime_types:
  - audio/aac
  - audio/flac
  - audio/mpeg
  - audio/ogg
  - audio/wav
  - video/mp4
  - video/mpeg
  - video/ogg
  - video/webm
  - video/x-matroska
