---
- name: Install opencode
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail
      source "{{ user_home }}/.nvm/nvm.sh"
      npm i -g opencode-ai
    executable: /bin/bash
  become: true
  become_user: "{{ user_name }}"
