---
- name: Grub-btrfs | Install packages
  ansible.builtin.package:
    name: "{{ system_grub_btrfs_packages }}"
    state: present
  when:
    - system_grub_btrfs_manage_packages
    - system_grub_btrfs_packages | length > 0
  notify: Update grub

- name: Grub-btrfs | Enable and start daemon
  ansible.builtin.systemd:
    name: "{{ system_grub_btrfs_service }}"
    enabled: "{{ system_grub_btrfs_enable_daemon }}"
    state: "{{ 'started' if system_grub_btrfs_enable_daemon else 'stopped' }}"
  when: system_grub_btrfs_service | length > 0
