---
- name: Gaming | Configure Debian i386 support
  when:
    - ansible_facts["os_family"] == "Debian"
    - >
      ('steam' in home_gaming_packages) or
      ('wine' in home_gaming_packages) or
      ('winetricks' in home_gaming_packages)
  block:
    - name: Gaming | Check Debian foreign architectures
      ansible.builtin.command:
        cmd: dpkg --print-foreign-architectures
      register: home_gaming_debian_foreign_architectures
      changed_when: false

    - name: Gaming | Enable Debian i386 architecture
      ansible.builtin.command:
        cmd: dpkg --add-architecture i386
      register: home_gaming_debian_i386_architecture
      changed_when: true
      when: "'i386' not in home_gaming_debian_foreign_architectures.stdout_lines"

    - name: Gaming | Update apt cache after enabling i386
      ansible.builtin.apt:
        update_cache: true
      when: home_gaming_debian_i386_architecture.changed | default(false)

- name: Gaming | Configure Arch multilib support
  when:
    - ansible_facts["os_family"] == "Archlinux"
    - "'steam' in home_gaming_packages"
  block:
    - name: Gaming | Check Arch pacman repositories
      ansible.builtin.command:
        cmd: pacman-conf --repo-list
      register: home_arch_pacman_repositories
      changed_when: false

    - name: Gaming | Enable Arch multilib repository for Steam
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        marker: "# {mark} ANSIBLE MANAGED MULTILIB"
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
      register: home_arch_multilib_repository
      when: "'multilib' not in home_arch_pacman_repositories.stdout_lines"

    - name: Gaming | Update pacman cache after enabling multilib
      community.general.pacman:
        update_cache: true
      when: home_arch_multilib_repository.changed | default(false)

- name: Gaming | Install packages
  ansible.builtin.package:
    name: "{{ home_gaming_packages }}"
    state: present
