---
- name: Gaming | Install packages
  ansible.builtin.package:
    name: "{{ gaming_packages }}"
    state: present
  when: gaming_packages | default([]) | length > 0

- name: Gaming | Install Flatpaks
  community.general.flatpak:
    name: "{{ gaming_flatpaks }}"
    state: present
    remote: flathub
  when: gaming_flatpaks | default([]) | length > 0

