---
mihon_desktop_dest: "{{ user_home }}/.local/share/applications/mihon.desktop"
mihon_icon_dest: "{{ user_home }}/.local/share/icons/mihon.png"
mihon_url: "https://mihon.org"
mihon_icon_url: "https://mihon.org/favicon-96x96.png"
mihon_icon_fallback_src: "{{ playbook_dir }}/../../assets/mihon.png"
mihon_browser: "brave"
mihon_wm_class: "brave-mihon.org__-Default"
