---
- name: Splashboot | Install packages
  community.general.pacman:
    name: "{{ splashboot_packages }}"
    state: present
  notify: Splashboot | Update initramfs
  when: splashboot_packages | length > 0
