---
- name: Splashboot | Install packages
  ansible.builtin.apt:
    name: "{{ splashboot_packages }}"
    state: present
  notify: Splashboot | Update initramfs
  when: splashboot_packages | length > 0
