---
- name: Splashboot | Install packages
  ansible.builtin.apt:
    name: "{{ system_splashboot_packages }}"
    state: present
  notify: Splashboot | Update initramfs
  when: system_splashboot_packages | length > 0
