---
- name: "Splashboot | Run {{ ansible_facts.os_family }} tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Splashboot | Check available Plymouth themes
  ansible.builtin.command:
    cmd: plymouth-set-default-theme --list
  register: system_plymouth_themes
  changed_when: false
  failed_when: false

- name: Splashboot | Check current Plymouth theme
  ansible.builtin.command:
    cmd: plymouth-set-default-theme
  register: system_plymouth_current_theme
  changed_when: false
  failed_when: false

- name: Splashboot | Set Plymouth theme
  ansible.builtin.command:
    cmd: "plymouth-set-default-theme {{ system_splashboot_theme }}"
  changed_when: true
  notify: Splashboot | Update initramfs
  when:
    - system_plymouth_themes.rc == 0
    - system_splashboot_theme in system_plymouth_themes.stdout_lines
    - system_plymouth_current_theme.stdout != system_splashboot_theme

- name: Splashboot | Merge GRUB splash options
  ansible.builtin.set_fact:
    system_grub_cmdline_linux_default: >-
      {{
        (
          (system_grub_cmdline_linux_default | default('')).split()
          + (system_splashboot_grub_options | default([]))
        )
        | unique
        | join(' ')
      }}
