---
- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Symlink identity include files to home
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    force: true
  loop: "{{ git_identities }}"
  become: false
  become_user: "{{ user_name }}"
