---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install \
            -r ansible/requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.1.3
        with:
          working_directory: ansible

  integration:
    name: Integration (${{ matrix.name }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 24.04
            dockerfile: Dockerfile.ubuntu
          - name: Arch Linux
            dockerfile: Dockerfile.archlinux
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build and run
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          docker build \
            --secret id=sops_age_key,env=SOPS_AGE_KEY \
            -f docker/${{ matrix.dockerfile }} \
            .
