---
- name: Office | Install
  ansible.builtin.include_role:
    name: lib/install
    tasks_from: packages
  vars:
    install_label: Office
    install_pacman_packages: "{{ office_pacman_packages }}"
